# Generated by Django 3.1.2 on 2020-11-16 01:31

from django.db import migrations, models
import web.apps.commons.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('face_login', models.ImageField(blank=True, null=True, upload_to=web.apps.commons.utils.RandomFileName('upload/check_in_out/face_login'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('face_logout', models.ImageField(blank=True, null=True, upload_to=web.apps.commons.utils.RandomFileName('upload/check_in_out/face_logout'))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
