# Generated by Django 3.1.2 on 2020-11-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle', '0002_motorcycle_profile'),
        ('checkinout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='motorcycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motorcycle.motorcycle'),
        ),
    ]
