# Generated by Django 3.1.2 on 2020-11-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkinout', '0003_remove_checkin_motorcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='plate',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
