# Generated by Django 3.1.2 on 2020-11-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkinout', '0004_checkin_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='plate',
        ),
    ]
