# Generated by Django 3.1.2 on 2020-11-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkinout', '0005_remove_checkin_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='plate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
