# Generated by Django 3.1.2 on 2020-11-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkinout', '0006_checkin_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='plate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
