# Generated by Django 3.1.2 on 2020-10-13 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.apps.commons.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('file', models.FileField(blank=True, null=True, upload_to=web.apps.commons.utils.RandomFileName('upload/data_import'))),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importfile_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importfile_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Updated User')),
            ],
            options={
                'verbose_name': 'Import File',
                'verbose_name_plural': 'Import Files',
            },
        ),
    ]
