# Generated by Django 3.1.2 on 2020-10-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('motorcycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorcycle_profile', to='user_profile.userprofile'),
        ),
    ]
