# Generated by Django 3.1.2 on 2020-11-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkinout', '0001_initial'),
        ('parking', '0002_park_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkinout.checkin'),
        ),
        migrations.AddField(
            model_name='park',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkinout.checkout'),
        ),
    ]
