# Generated by Django 3.1.2 on 2020-11-22 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('parking', '0003_auto_20201116_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='user_profile.userprofile'),
        ),
    ]
