# Generated by Django 3.1.2 on 2020-10-13 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.apps.commons.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('image', models.ImageField(blank=True, null=True, upload_to=web.apps.commons.utils.RandomFileName('upload/user_profile'))),
                ('family_name', models.CharField(db_index=True, max_length=50)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=15)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Updated User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
